### ISSUE TITLE
Missing default Helm annotations

### ISSUE THREAD

**Issue by bartjkdp** [Amsterdam/openstad-kubernetes#11]
Helm charts by default have a number of annotations:

```yaml
  labels:
    app.kubernetes.io/instance: hallo-wereld
    app.kubernetes.io/name: hallo-wereld
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: hallo-wereld-0.1.0
```

I am missing these annotations on the Openstad deployments. We should probably use the default helpers for this:

```yaml
{{/*
Common labels
*/}}
{{- define "hallo-wereld.labels" -}}
helm.sh/chart: {{ include "hallo-wereld.chart" . }}
{{ include "hallo-wereld.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}

{{/*
Selector labels
*/}}
{{- define "hallo-wereld.selectorLabels" -}}
app.kubernetes.io/name: {{ include "hallo-wereld.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
```

See an example chart when using `helm create <chartname>`.

We could use `app.kubernetes.io/component` to identify a specific component.

**Comment by S-Nigel** [comment]
Hello @bartjkdp,

Thanks for reporting this issue. I have a little bit of trouble understanding how this works. I followed [the documentation on common labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/). I have also used the [prometheus](https://github.com/helm/charts/tree/master/stable/prometheus) project as a reference.

I have added the labels using the given helper template and this results in my debug-log:

```
metadata:
    labels:
        helm.sh/chart: openstad-0.2.0
        app.kubernetes.io/name: openstad
        app.kubernetes.io/instance: openstad
        app.kubernetes.io/version: "1"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: openstad-api-deployment
```
Or preferable, this is currently in the template that generates the labels above:
```
metadata:
    labels:
        {{- include "openstad.labels" . | nindent 4 }}
         app.kubernetes.io/component: {{ template "openstad.api.fullname" . }}-deployment
```

However, when I install and uninstall the chart I still get the following:
```
$ helm uninstall openstad
manifest-10
manifest-11
manifest-12
manifest-3
manifest-4
manifest-5
manifest-6
manifest-7
manifest-8
manifest-9
```

Do you know what I am doing wrong in this case? Or do you have an article I read about how I can do it correctly?
