### ISSUE TITLE
Certificates don't seem to be issued. Turning on CluserIssuer gives an error with installing/upgrading

### ISSUE THREAD

**Issue by ToshKoevoets** [Amsterdam/openstad-kubernetes#25]
When turning on ClusterIssuers in values an error is given
```
## Settings for Cert-Manager/Cluster issuer
clusterIssuer:
  enabled: true  # Whether this issuer is created
```
On helm install or upgrade following error is given:

`Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ClusterIssuer" in version "cert-manager.io/v1alpha3"
`

Dependecy Cert-manager is set to true and installed

```
dependencies:
  ## Database
  mongodb:
    enabled: true
  mysql:
    enabled: true

  ## SSL
  cert-manager:
    enabled: true

```
