### ISSUE TITLE
Secure/same site cookies are not being set in auth service

### ISSUE THREAD

**Issue by ToshKoevoets** [Amsterdam/openstad-kubernetes#38]
As soon as the cookie gets the flag secure/httpOnly it doesn't get set. I'm not sure which flag it is yet. Will debug further but it's probably something to do with the way nginx is setup or domain names are structured.

COOKIE_SECURE_OFF to yes works, when turned off it doesn;t work

```
app.set('trust proxy', '127.0.0.1');


const sessionConfig = {
  saveUninitialized : true,
  resave            : true,
  secret            : config.session.secret,
  store             : sessionStore,
  key               : 'authorization.sid',
  cookie            : {
    maxAge: config.session.maxAge,
    secure: process.env.COOKIE_SECURE_OFF ===  'yes' ? false : true,
    httpOnly: process.env.COOKIE_SECURE_OFF ===  'yes' ? false : true,
    sameSite: false, 
  },

};
```

**Comment by jaapgorjup** [comment]
According to reference cases it is that the value of the x-forwarded-scheme http is not there.
Standard this should be set on the Nginx controller using x-forwarded-for in the general configuration.
But this is not good since it is shared and not per Ingress.

The alternative is adding annotations to the Ingress for Nginx to add the variables:
```
    nginx.ingress.kubernetes.io/configuration-snippet: |
      set $http_x_forwarded_proto "https";
      set $http_x_forwarded_port "443";
```

This is an example of an echo service that returns all the request data.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echochamber
  name: echochamber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echochamber
  template:
    metadata:
      labels:
        app: echochamber
    spec:
      containers:
      - image: brndnmtthws/nginx-echo-headers
        name: nginx-echo-headers
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: echochamber-service
spec:
  ports:
  - port: 8080
  selector:  
    app: echochamber

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echochamber-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      set $http_x_forwarded_proto "https";
      set $http_x_forwarded_port "443";
spec:
  rules:
  - host: FILL.IN.YOUR.HOSTNAME
    http:
      paths:
      - path: /
        backend:
          serviceName: echochamber-service
          servicePort: 8080
```
