### ISSUE TITLE
Secrets allows for name change in  files assumes default

### ISSUE THREAD

**Issue by ToshKoevoets** [Amsterdam/openstad-kubernetes#40]
I have no desire to change the name of the secret, but currently it's possible through the values and if done it breaks the installation

```
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.database.secretName | default "openstad-db-credentials" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{ template "databaseSecret" . }}

```

```
          env:
            - name: DB_TYPE
              value: mysql
            - name: API_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: openstad-db-credentials
            - name: API_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: openstad-db-credentials
            - name: API_DATABASE_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database
                  name: openstad-api-db
            - name: API_DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  key: hostname
                  name: openstad-db-credentials
```
