### ISSUE TITLE
Add serviceaccount to default Charts

### ISSUE THREAD

**Issue by ToshKoevoets** [Amsterdam/openstad-kubernetes#41]
This is integral part of the application, is it possible to add service account to the default installation instead of setting up manually? Otherwise we will have to add it to installatino documentation]

If added service account name in the admin deployment and it's working.

```

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openstad
  name: openstad-ingress-update-role
rules:
  - apiGroups: ['extensions','networking.k8s.io']
    resources: ['ingresses']
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
  - apiGroups: ['networking.k8s.io']
    resources: ['ingressclasses']
    verbs: ["get", "list", "watch"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openstad
  name: openstad-ingress-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openstad-ingress-update-rb
  namespace: openstad
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openstad-ingress-update-role
subjects:
  - kind: ServiceAccount
    name: openstad-ingress-sa
```

**Comment by jaapgorjup** [comment]
Your question is to add the RoleBinding to the default serviceaccount for the namespace. That means that all containers running in that namespace have this Role and can perform this action. 
Since this is a typical admin action I would not recommend sharing this with all the applications. But if the use case fits you can do this:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openstad-ingress-update-rb
  namespace: openstad
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openstad-ingress-update-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: openstad
```
