### ISSUE TITLE
Configure ingress definitions similar to default Helm chart structure

### ISSUE THREAD

**Issue by bartjkdp** [Amsterdam/openstad-kubernetes#9]
It would be nice if configuring ingress definitions work similarly to default Helm charts (and default chart of `helm create`:

```yaml
  ingress:
    enabled: false
    annotations: {}
    #   kubernetes.io/ingress.class: nginx
    #   kubernetes.io/tls-acme: 'true'

    extraLabels: {}

    hosts: []
    #   - alertmanager.domain.com
    #   - domain.com/alertmanager

    tls: []
    #   - secretName: prometheus-alerts-tls
    #     hosts:
    #       - alertmanager.domain.com`
```

From: https://github.com/helm/charts/blob/master/stable/prometheus/values.yaml

In this way we can omit `define.certManager.clusterIssuer` and set annotations using `ingress.annotations`.
